//! Web UI channel — Phase 39.
//!
//! A localhost-only web chat interface that connects to the daemon
//! over the existing IPC protocol via WebSocket. The web server is
//! a background task spawned inside `run_daemon` (same pattern as
//! the webhook listener). Each WebSocket connection bridges directly
//! to the daemon's Unix socket at the frame level — sending
//! `FrontendMessage` frames and forwarding `DaemonEnvelope` frames
//! in real time.
//!
//! `WebDaemonChannel` is the `ChannelContext` stub returned by the
//! daemon's `ChannelFactory` when a `FrontendType::Web` connection
//! arrives. Like `TelegramDaemonChannel`, its `stream_event` and
//! `finalize` are no-ops — the `IpcChannelBridge` handles
//! forwarding those over IPC.

use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};

use futures_util::{SinkExt, StreamExt};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::{TcpListener, UnixStream};

use aivyx_core::{
    CancellationToken, ChannelContext, ChannelError, ChannelPlatform, SessionId, StreamEvent,
    TurnOutcome,
};

use crate::daemon_server::DaemonError;
use crate::daemon_ipc::{
    decode_frame, encode_frame, DaemonEnvelope, FrameError, FrontendMessage, FrontendType,
};
use crate::notify_webui::{DesktopNotificationFrame, WebUiBroadcaster};

/// Default web UI port. Adjacent to webhook (7842).
pub const DEFAULT_WEB_UI_PORT: u16 = 7843;

/// Legacy single-file chat frontend. Chapter M serves the Dioxus
/// `aivyx-web` bundle when it's built; this is the fallback at `/` while the
/// bundle is absent (and until the WASM app reaches chat parity, M.6).
const HTML: &str = include_str!("web_ui_static.html");

// Chapter M.5 — the embedded Dioxus bundle, generated by `build.rs` from
// `crates/aivyx-web/dist/` (or an empty table when it hasn't been built).
include!(concat!(env!("OUT_DIR"), "/web_assets.rs"));

/// Look up an embedded bundle asset by request path (e.g. `/aivyx-web_bg.wasm`).
fn web_asset(path: &str) -> Option<(&'static [u8], &'static str)> {
    WEB_ASSETS
        .iter()
        .find(|(p, _, _)| *p == path)
        .map(|(_, bytes, mime)| (*bytes, *mime))
}

/// The bundle's `index.html`, when the bundle is built.
fn bundle_index() -> Option<(&'static [u8], &'static str)> {
    web_asset("/index.html")
}

// ---------------------------------------------------------------------------
// WebDaemonChannel — identity stub for the daemon's ChannelFactory
// ---------------------------------------------------------------------------

/// Lightweight `ChannelContext` stub that returns `Trusted` trust
/// tier and `Local` platform. Used by the daemon's `ChannelFactory`
/// when a `FrontendType::Web` connection arrives. The stub's
/// `stream_event` and `finalize` are no-ops — the `IpcChannelBridge`
/// handles forwarding those over IPC.
///
/// `ChannelPlatform::Local` is correct because the web UI is bound
/// to `127.0.0.1` only — the existing `Local` doc says "CLI,
/// desktop app, local REST on 127.0.0.1."
pub struct WebDaemonChannel {
    session: SessionId,
    /// Rotated per turn by [`reset_cancellation`] and fired by
    /// [`cancel_inflight`]. See `TelegramDaemonChannel::token` —
    /// same C1+H1 audit fix.
    token: Mutex<CancellationToken>,
}

impl WebDaemonChannel {
    pub fn new() -> Self {
        WebDaemonChannel {
            session: SessionId::new(),
            token: Mutex::new(CancellationToken::new()),
        }
    }
}

impl Default for WebDaemonChannel {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait::async_trait]
impl ChannelContext for WebDaemonChannel {
    fn channel_name(&self) -> &str {
        "aivyx-web"
    }

    fn platform(&self) -> ChannelPlatform {
        ChannelPlatform::Local
    }

    fn trust_tier(&self) -> aivyx_capability::TrustTier {
        aivyx_capability::TrustTier::Trusted
    }

    fn session_id(&self) -> SessionId {
        self.session
    }

    async fn stream_event(&self, _event: StreamEvent<'_>) -> Result<(), ChannelError> {
        Ok(())
    }

    async fn finalize(&self, _outcome: &TurnOutcome) -> Result<(), ChannelError> {
        Ok(())
    }

    fn cancellation_token(&self) -> CancellationToken {
        self.token.lock().expect("token mutex poisoned").clone()
    }

    fn reset_cancellation(&self) {
        let mut slot = self.token.lock().expect("token mutex poisoned");
        *slot = CancellationToken::new();
    }

    fn cancel_inflight(&self) {
        self.token.lock().expect("token mutex poisoned").cancel();
    }
}

// ---------------------------------------------------------------------------
// Web UI HTTP + WebSocket server
// ---------------------------------------------------------------------------

/// Run the web UI server. Binds `127.0.0.1:<port>`, serves the
/// embedded HTML at `GET /`, and upgrades `GET /ws` to WebSocket.
/// Each WS connection bridges to the daemon's Unix socket at
/// `socket_path`.
///
/// Uses `tokio-tungstenite` directly on the TCP stream — each
/// incoming connection is peeked to determine if it's a WebSocket
/// upgrade request for `/ws` or an HTTP request for `/`. This
/// avoids pulling hyper into the WebSocket path.
///
/// This future never returns normally — it runs until `shutdown` is
/// cancelled.
pub async fn run_web_ui_server(
    socket_path: PathBuf,
    port: u16,
    shutdown: CancellationToken,
    web_ui_broadcaster: Option<Arc<WebUiBroadcaster>>,
) -> Result<(), DaemonError> {
    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], port));
    let listener = TcpListener::bind(addr)
        .await
        .map_err(|source| DaemonError::Bind {
            path: addr.to_string(),
            source,
        })?;

    eprintln!("aivyx web ui: listening on http://{addr}");

    let socket_path = Arc::new(socket_path);

    loop {
        let (stream, _remote) = tokio::select! {
            result = listener.accept() => {
                match result {
                    Ok(conn) => conn,
                    Err(e) => {
                        eprintln!("aivyx web ui: accept error: {e}");
                        continue;
                    }
                }
            }
            _ = shutdown.cancelled() => return Ok(()),
        };

        let conn_socket_path = Arc::clone(&socket_path);
        let conn_broadcaster = web_ui_broadcaster.clone();

        tokio::spawn(async move {
            if let Err(e) =
                handle_connection(stream, &conn_socket_path, conn_broadcaster).await
            {
                eprintln!("aivyx web ui: connection error: {e}");
            }
        });
    }
}

/// Handle a single TCP connection. Peek at the first bytes to
/// determine the HTTP path, then either serve HTML or upgrade to
/// WebSocket.
async fn handle_connection(
    stream: tokio::net::TcpStream,
    socket_path: &Path,
    web_ui_broadcaster: Option<Arc<WebUiBroadcaster>>,
) -> Result<(), DaemonError> {
    // Peek at the HTTP request line to determine the path.
    // We read up to 1024 bytes to get the full request line.
    let mut peek_buf = [0u8; 1024];
    let n = stream
        .peek(&mut peek_buf)
        .await?;
    let request_line = String::from_utf8_lossy(&peek_buf[..n]);

    if request_line.starts_with("GET /ws") {
        // WebSocket upgrade — let tokio-tungstenite handle the
        // HTTP 101 handshake and the WebSocket framing.
        let ws_stream = tokio_tungstenite::accept_async(stream)
            .await
            .map_err(|e| DaemonError::WebSocket(format!("ws handshake: {e}")))?;

        handle_websocket(ws_stream, socket_path, web_ui_broadcaster).await
    } else {
        // Static HTTP: serve the embedded Dioxus bundle, falling back to the
        // legacy page at `/` while the bundle is unbuilt.
        serve_static(stream, request_path(&request_line)).await
    }
}

/// Extract the request-target path (no query string) from the HTTP request
/// line, e.g. `GET /aivyx-web_bg.wasm?v=1 HTTP/1.1` → `/aivyx-web_bg.wasm`.
fn request_path(request_line: &str) -> String {
    request_line
        .split_whitespace()
        .nth(1)
        .unwrap_or("/")
        .split('?')
        .next()
        .unwrap_or("/")
        .to_string()
}

/// Serve a static asset over plain HTTP (Chapter M.5).
///
/// `/` → the bundle's `index.html` when built, else the legacy chat page (the
/// fallback). Any other path is looked up in the embedded bundle and served
/// with its content-type; a miss is a 404.
async fn serve_static(stream: tokio::net::TcpStream, path: String) -> Result<(), DaemonError> {
    // `/classic` always serves the legacy single-file inspection UI (audit /
    // memory / learning / proposals / notifications / sessions) — the panes the
    // Dioxus app hasn't ported yet (Chapter M ships Missions + Chat). The new
    // app links to it so building the bundle never loses a pane.
    if path == "/classic" {
        return serve_bytes(stream, "200 OK", "text/html; charset=utf-8", HTML.as_bytes()).await;
    }
    if path == "/" || path == "/index.html" {
        return match bundle_index() {
            Some((bytes, mime)) => serve_bytes(stream, "200 OK", mime, bytes).await,
            // No bundle built → the legacy page is the whole UI.
            None => serve_bytes(stream, "200 OK", "text/html; charset=utf-8", HTML.as_bytes()).await,
        };
    }
    match web_asset(&path) {
        Some((bytes, mime)) => serve_bytes(stream, "200 OK", mime, bytes).await,
        None => serve_bytes(stream, "404 Not Found", "text/plain", b"not found").await,
    }
}

/// Write one plain-HTTP response (status line + headers + body, `Connection:
/// close`). `application/wasm` etc. flow through `content_type` so the browser
/// streams + compiles the wasm correctly.
async fn serve_bytes(
    mut stream: tokio::net::TcpStream,
    status: &str,
    content_type: &str,
    body: &[u8],
) -> Result<(), DaemonError> {
    let response = format!(
        "HTTP/1.1 {status}\r\n\
         Content-Type: {content_type}\r\n\
         Content-Length: {}\r\n\
         Connection: close\r\n\
         \r\n",
        body.len()
    );
    stream.write_all(response.as_bytes()).await?;
    stream.write_all(body).await?;
    stream.flush().await?;
    // Graceful close. `handle_connection` only *peeks* the request line, so the
    // client's request bytes are still unread in the receive buffer. Dropping
    // the socket now would make the OS send a TCP RST instead of a FIN, and that
    // RST can race ahead and truncate a large in-flight body (e.g. the ~1.7 MB
    // wasm — small assets finish before it matters, the wasm did not, which left
    // the browser with a half-streamed module and a blank page). Half-close the
    // write side (FIN), then drain the read side to EOF so the close is clean.
    let _ = stream.shutdown().await;
    let mut sink = [0u8; 1024];
    let _ = tokio::time::timeout(std::time::Duration::from_secs(5), async {
        while let Ok(n) = stream.read(&mut sink).await {
            if n == 0 {
                break;
            }
        }
    })
    .await;
    Ok(())
}

// ---------------------------------------------------------------------------
// WebSocket ↔ daemon IPC bridge
// ---------------------------------------------------------------------------

/// Bridge a single WebSocket connection to the daemon's Unix socket.
/// Runs two concurrent loops:
/// 1. WS→IPC: reads JSON from WebSocket, encodes as IPC frames,
///    sends to the daemon.
/// 2. IPC→WS: reads IPC frames from the daemon, sends JSON over WS.
async fn handle_websocket(
    ws_stream: tokio_tungstenite::WebSocketStream<tokio::net::TcpStream>,
    socket_path: &Path,
    web_ui_broadcaster: Option<Arc<WebUiBroadcaster>>,
) -> Result<(), DaemonError> {
    // Connect to the daemon's Unix socket.
    let unix_stream = UnixStream::connect(socket_path).await?;
    let (mut unix_reader, mut unix_writer) = unix_stream.into_split();

    // Read DaemonReady from the daemon.
    let mut ipc_buf = Vec::with_capacity(4096);
    loop {
        let mut tmp = [0u8; 4096];
        let n = unix_reader.read(&mut tmp).await?;
        if n == 0 {
            return Err(DaemonError::Protocol(
                "daemon disconnected before DaemonReady".into(),
            ));
        }
        ipc_buf.extend_from_slice(&tmp[..n]);
        match decode_frame::<DaemonEnvelope>(&ipc_buf) {
            Ok((DaemonEnvelope::DaemonReady { .. }, consumed)) => {
                ipc_buf.drain(..consumed);
                break;
            }
            Err(FrameError::IncompleteBuf) => continue,
            Ok((other, _)) => {
                return Err(DaemonError::Protocol(format!(
                    "expected DaemonReady, got {other:?}"
                )));
            }
            Err(e) => return Err(e.into()),
        }
    }

    // Send StartSession with FrontendType::Web.
    let start = FrontendMessage::StartSession {
        role: None,
        frontend_type: Some(FrontendType::Web),
    };
    let frame = encode_frame(&start)?;
    unix_writer.write_all(&frame).await?;

    // Read SessionStarted — forward it to the WebSocket as JSON.
    let session_id: String = loop {
        let mut tmp = [0u8; 4096];
        let n = unix_reader.read(&mut tmp).await?;
        if n == 0 {
            return Err(DaemonError::Protocol(
                "daemon disconnected before SessionStarted".into(),
            ));
        }
        ipc_buf.extend_from_slice(&tmp[..n]);
        match decode_frame::<DaemonEnvelope>(&ipc_buf) {
            Ok((DaemonEnvelope::SessionStarted { session_id }, consumed)) => {
                ipc_buf.drain(..consumed);
                break session_id;
            }
            // The daemon delivers a take-once `RecoveryNotice` between
            // `DaemonReady` and `SessionStarted` to the first frontend
            // that connects after an unclean shutdown (a prior instance
            // crashed / was killed rather than stopped cleanly). It is
            // informational — skip past it and keep waiting for
            // `SessionStarted`. Without this arm the first browser to
            // connect after an unclean shutdown fails the handshake with
            // "expected SessionStarted, got RecoveryNotice" (mirrors the
            // same tolerance the REPL/TUI client already has).
            Ok((DaemonEnvelope::RecoveryNotice { .. }, consumed)) => {
                ipc_buf.drain(..consumed);
                continue;
            }
            Err(FrameError::IncompleteBuf) => continue,
            Ok((other, _)) => {
                return Err(DaemonError::Protocol(format!(
                    "expected SessionStarted, got {other:?}"
                )));
            }
            Err(e) => return Err(e.into()),
        }
    };

    // Split the WebSocket stream. The sink is shared with the
    // optional broadcast relay loop (Phase 69 Task 5), so wrap it
    // behind a Mutex like the unix writer.
    let (ws_sink, mut ws_source) = ws_stream.split();
    let ws_sink = Arc::new(tokio::sync::Mutex::new(ws_sink));

    // Send SessionStarted to the browser.
    let session_started_json = serde_json::json!({
        "type": "SessionStarted",
        "session_id": session_id,
    });
    {
        let mut sink = ws_sink.lock().await;
        let _ = sink
            .send(tokio_tungstenite::tungstenite::Message::Text(
                session_started_json.to_string().into(),
            ))
            .await;
    }

    // Three concurrent loops: WS→IPC, IPC→WS, and (when a
    // broadcaster is configured) Broadcast→WS for Phase 69
    // desktop notifications.
    let unix_writer = Arc::new(tokio::sync::Mutex::new(unix_writer));

    // IPC→WS: read daemon frames, forward as JSON over WebSocket.
    let ipc_to_ws = {
        let ws_sink = Arc::clone(&ws_sink);
        async move {
            let mut buf = ipc_buf; // reuse the buffer from handshake
            loop {
                // Try to decode any buffered frames first.
                loop {
                    match decode_frame::<DaemonEnvelope>(&buf) {
                        Ok((envelope, consumed)) => {
                            buf.drain(..consumed);
                            let json = match serde_json::to_string(&envelope) {
                                Ok(j) => j,
                                Err(e) => {
                                    eprintln!("aivyx web ui: serialize error: {e}");
                                    continue;
                                }
                            };
                            let mut sink = ws_sink.lock().await;
                            if sink
                                .send(tokio_tungstenite::tungstenite::Message::Text(
                                    json.into(),
                                ))
                                .await
                                .is_err()
                            {
                                return; // WebSocket closed
                            }
                        }
                        Err(FrameError::IncompleteBuf) => break,
                        Err(e) => {
                            eprintln!("aivyx web ui: ipc decode error: {e}");
                            return;
                        }
                    }
                }

                // Read more bytes from the daemon.
                let mut tmp = [0u8; 4096];
                match unix_reader.read(&mut tmp).await {
                    Ok(0) => return, // daemon disconnected
                    Ok(n) => buf.extend_from_slice(&tmp[..n]),
                    Err(_) => return,
                }
            }
        }
    };

    // WS→IPC: read JSON from WebSocket, encode as IPC frames, send
    // to daemon.
    let ws_to_ipc = {
        let unix_writer = Arc::clone(&unix_writer);
        async move {
            while let Some(msg_result) = ws_source.next().await {
                let msg = match msg_result {
                    Ok(m) => m,
                    Err(_) => return, // WebSocket error
                };

                let text = match msg {
                    tokio_tungstenite::tungstenite::Message::Text(t) => t,
                    tokio_tungstenite::tungstenite::Message::Close(_) => return,
                    _ => continue, // ignore binary, ping, pong
                };

                // Parse as FrontendMessage and re-encode as IPC frame.
                let frontend_msg: FrontendMessage = match serde_json::from_str(&text) {
                    Ok(m) => m,
                    Err(e) => {
                        eprintln!("aivyx web ui: invalid WS message: {e}");
                        continue;
                    }
                };

                let frame = match encode_frame(&frontend_msg) {
                    Ok(f) => f,
                    Err(e) => {
                        eprintln!("aivyx web ui: encode error: {e}");
                        continue;
                    }
                };

                let mut w = unix_writer.lock().await;
                if w.write_all(&frame).await.is_err() {
                    return; // daemon disconnected
                }
            }
        }
    };

    // Broadcast→WS (Phase 69 Task 5): if a WebUiBroadcaster is
    // configured, subscribe a fresh receiver and relay every
    // DesktopNotificationFrame onto the WS as
    // DaemonEnvelope::DesktopNotification. On `Lagged` we drop
    // the missed frames silently — desktop notifications for a
    // tab the operator isn't watching are by definition
    // discardable.
    let broadcast_to_ws = {
        let ws_sink = Arc::clone(&ws_sink);
        let mut rx_opt = web_ui_broadcaster.as_ref().map(|bc| bc.subscribe());
        async move {
            let Some(rx) = rx_opt.as_mut() else {
                // No broadcaster wired — this future never
                // completes, so the `select!` only fires on the
                // other two arms.
                std::future::pending::<()>().await;
                return;
            };
            loop {
                match rx.recv().await {
                    Ok(DesktopNotificationFrame { title, body }) => {
                        let envelope = DaemonEnvelope::DesktopNotification { title, body };
                        let json = match serde_json::to_string(&envelope) {
                            Ok(j) => j,
                            Err(e) => {
                                eprintln!("aivyx web ui: broadcast serialize error: {e}");
                                continue;
                            }
                        };
                        let mut sink = ws_sink.lock().await;
                        if sink
                            .send(tokio_tungstenite::tungstenite::Message::Text(
                                json.into(),
                            ))
                            .await
                            .is_err()
                        {
                            return; // WebSocket closed
                        }
                    }
                    Err(tokio::sync::broadcast::error::RecvError::Lagged(_)) => {
                        // Skipped some frames; keep listening.
                        continue;
                    }
                    Err(tokio::sync::broadcast::error::RecvError::Closed) => return,
                }
            }
        }
    };

    // Run all three loops concurrently. When any exits, the
    // connection is done.
    tokio::select! {
        _ = ipc_to_ws => {}
        _ = ws_to_ipc => {}
        _ = broadcast_to_ws => {}
    }

    // Send Disconnect to the daemon (best effort).
    if let Ok(frame) = encode_frame(&FrontendMessage::Disconnect) {
        let mut w = unix_writer.lock().await;
        let _ = w.write_all(&frame).await;
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn web_channel_platform_is_local() {
        let ch = WebDaemonChannel::new();
        assert_eq!(ch.platform(), ChannelPlatform::Local);
    }

    #[test]
    fn request_path_extracts_target_without_query() {
        assert_eq!(request_path("GET / HTTP/1.1"), "/");
        assert_eq!(
            request_path("GET /aivyx-web_bg.wasm HTTP/1.1"),
            "/aivyx-web_bg.wasm"
        );
        assert_eq!(request_path("GET /app.js?v=abc123 HTTP/1.1"), "/app.js");
        assert_eq!(request_path("garbage"), "/");
    }

    #[test]
    fn web_asset_lookup_finds_index_and_misses_unknown_paths() {
        // Since Chapter R the `aivyx-web/dist/` bundle is committed and embedded
        // by build.rs, so the table is populated: `/index.html` resolves (the
        // SPA entry the daemon serves at `/`), while an unknown path misses
        // (→ 404). `WEB_ASSETS` is `&[]` only in the degenerate build where
        // dist/ was deleted — not the shipped configuration.
        assert!(
            bundle_index().is_some(),
            "the committed dist/ bundle must embed index.html",
        );
        assert!(web_asset("/index.html").is_some());
        assert!(
            web_asset("/definitely-not-an-asset.js").is_none(),
            "unknown asset paths miss",
        );
    }

    #[test]
    fn web_channel_trust_tier_is_trusted() {
        let ch = WebDaemonChannel::new();
        assert_eq!(ch.trust_tier(), aivyx_capability::TrustTier::Trusted);
    }

    #[test]
    fn web_channel_name() {
        let ch = WebDaemonChannel::new();
        assert_eq!(ch.channel_name(), "aivyx-web");
    }

    // Audit C1+H1 regression — same coverage as the
    // Telegram / Discord / Slack daemon stubs.
    #[test]
    fn cancel_inflight_then_reset_yields_fresh_token() {
        let ch = WebDaemonChannel::new();
        let stale = ch.cancellation_token();
        assert!(!stale.is_cancelled());
        ch.cancel_inflight();
        assert!(stale.is_cancelled(), "cancel_inflight fires the live token");
        ch.reset_cancellation();
        assert!(
            !ch.cancellation_token().is_cancelled(),
            "reset_cancellation installs a fresh token"
        );
        assert!(stale.is_cancelled(), "the pre-reset token stays cancelled");
    }

    #[test]
    fn default_port_is_7843() {
        assert_eq!(DEFAULT_WEB_UI_PORT, 7843);
    }

    #[test]
    fn html_is_non_empty() {
        assert!(!HTML.is_empty(), "embedded HTML must not be empty");
        assert!(HTML.contains("<html"), "embedded HTML must contain <html tag");
    }

    /// Phase 47 — the embedded HTML must wire the four inspection panes
    /// (chat / missions / audit / sessions) and the Query/QueryResponse
    /// JS layer. Pure substring smoke tests — they protect against
    /// accidental gutting of the tab strip during future refactors.
    #[test]
    fn html_contains_phase_47_tab_structure() {
        assert!(HTML.contains("data-pane=\"chat\""));
        assert!(HTML.contains("data-pane=\"missions\""));
        assert!(HTML.contains("data-pane=\"audit\""));
        assert!(HTML.contains("data-pane=\"sessions\""));
    }

    #[test]
    fn html_contains_phase_47_query_dispatch() {
        // The JS layer must build Query frames and handle QueryResponse.
        assert!(HTML.contains("'Query'"), "must construct Query frames");
        assert!(
            HTML.contains("'QueryResponse'"),
            "must dispatch on QueryResponse type"
        );
        // The three query kinds the UI auto-issues on tab activation.
        assert!(HTML.contains("'ListMissions'"));
        assert!(HTML.contains("'ListAuditEntries'"));
        assert!(HTML.contains("'ListSessions'"));
        assert!(HTML.contains("'VerifyAuditChain'"));
    }

    /// Phase 74 — the embedded HTML must wire the Memory pane:
    /// tab presence, the three query kinds, EvictMemoryTopic
    /// envelope construction, and the search bar. Substring
    /// smoke tests guard against accidental gutting of the
    /// memory-polish surface.
    #[test]
    fn html_contains_phase_74_memory_pane_wiring() {
        assert!(
            HTML.contains("data-pane=\"memory\""),
            "must declare the memory tab/pane"
        );
        assert!(
            HTML.contains("'ListMemoryTopics'"),
            "must dispatch ListMemoryTopics queries"
        );
        assert!(
            HTML.contains("'GetMemoryTopicEntries'"),
            "must dispatch GetMemoryTopicEntries queries"
        );
        assert!(
            HTML.contains("'SearchMemory'"),
            "must dispatch SearchMemory queries"
        );
        assert!(
            HTML.contains("'EvictMemoryTopic'"),
            "must construct EvictMemoryTopic envelopes"
        );
        assert!(
            HTML.contains("mem-search-input"),
            "must include the memory search bar"
        );
        assert!(
            HTML.contains("mem-semantic-toggle"),
            "must include the Phase 75 semantic search toggle"
        );
    }

    /// Phase 78 — the embedded HTML must wire the Learning
    /// pane: tab presence, query dispatch, and the body
    /// container the loader renders into.
    #[test]
    fn html_contains_phase_78_learning_pane_wiring() {
        assert!(
            HTML.contains("data-pane=\"learning\""),
            "must include the Learning tab/pane"
        );
        assert!(
            HTML.contains("'GetLearningInsights'"),
            "must dispatch GetLearningInsights queries"
        );
        assert!(
            HTML.contains("LearningInsights"),
            "must handle the LearningInsights response"
        );
        assert!(
            HTML.contains("learning-body"),
            "must include the Learning render container"
        );
        assert!(
            HTML.contains("function loadLearning"),
            "must define the Learning loader"
        );
        // Phase 79 (Q4a) — the Learning pane must surface the
        // adaptive-Persona last-selection.
        assert!(
            HTML.contains("payload.persona_selection"),
            "must read the persona_selection field"
        );
        assert!(
            HTML.contains("Adaptive Persona"),
            "must render the adaptive-Persona selection line"
        );
        // Phase 80 (Q4a) — the Learning pane must surface the
        // proactive-surfacing last-cycle stat.
        assert!(
            HTML.contains("payload.proactive"),
            "must read the proactive field"
        );
        assert!(
            HTML.contains("surfaced last cycle"),
            "must render the proactive last-cycle line"
        );
        // Phase 81 (Q4a) — the Learning pane must surface the
        // persona-lifecycle last-cycle stat.
        assert!(
            HTML.contains("payload.persona_lifecycle"),
            "must read the persona_lifecycle field"
        );
        assert!(
            HTML.contains("proposed last cycle"),
            "must render the persona-lifecycle last-cycle line"
        );
        // Phase 82 — the Learning pane must surface the durable
        // accumulated (decayed) helpfulness view.
        assert!(
            HTML.contains("payload.accumulated_helpfulness"),
            "must read the accumulated_helpfulness field"
        );
        assert!(
            HTML.contains(
                "Accumulated helpfulness (all-time, decayed)"
            ),
            "must render the accumulated-helpfulness card"
        );
        // Phase 83 — the Learning pane must surface the durable
        // cross-session co-occurrence patterns.
        assert!(
            HTML.contains("payload.cooccurrence"),
            "must read the cooccurrence field"
        );
        assert!(
            HTML.contains(
                "Topics that consistently help together"
            ),
            "must render the co-occurrence card"
        );
        // Phase 84 — the Learning pane must surface the
        // last-turn cluster-aware co-recall stat.
        assert!(
            HTML.contains("payload.cluster_recall"),
            "must read the cluster_recall field"
        );
        assert!(
            HTML.contains("Cluster co-recall (last turn)"),
            "must render the cluster-recall card"
        );
    }

    /// Phase 73 — the embedded HTML must wire the Notifications
    /// pane: tab presence, target-filter chip, query dispatch,
    /// and the five outcome badge classes (delivered, failed,
    /// skipped_empty_response, skipped_by_condition,
    /// skipped_by_rate_limit). Substring smoke tests guard
    /// against accidental gutting of the Tier-2 polish surface.
    #[test]
    fn html_contains_phase_73_notifications_pane_wiring() {
        assert!(
            HTML.contains("data-pane=\"notifications\""),
            "must declare the notifications tab/pane"
        );
        assert!(
            HTML.contains("'ListNotificationHistory'"),
            "must dispatch ListNotificationHistory queries"
        );
        assert!(
            HTML.contains("data-notif-target-filter=\"\""),
            "must include the all-targets filter chip"
        );
        // Five outcome badge classes — colour-coded per CSS.
        for badge in [
            "notif-outcome.delivered",
            "notif-outcome.failed",
            "notif-outcome.skipped_empty_response",
            "notif-outcome.skipped_by_condition",
            "notif-outcome.skipped_by_rate_limit",
        ] {
            assert!(
                HTML.contains(badge),
                "must style the {badge} outcome badge"
            );
        }
    }

    /// Phase 70 — the embedded HTML must wire the Proposals
    /// pane: tab presence, filter chips, ListPersonaProposals
    /// query dispatch, and ResolvePersonaProposal envelope
    /// construction with all three resolution variants.
    #[test]
    fn html_contains_phase_70_proposals_pane_wiring() {
        // Tab structure.
        assert!(
            HTML.contains("data-pane=\"proposals\""),
            "must declare the proposals tab/pane"
        );
        // Filter chips.
        assert!(
            HTML.contains("data-proposal-filter=\"pending\""),
            "must include a pending filter chip"
        );
        assert!(
            HTML.contains("data-proposal-filter=\"all\""),
            "must include an all-status filter chip"
        );
        // IPC dispatch.
        assert!(
            HTML.contains("'ListPersonaProposals'"),
            "must dispatch ListPersonaProposals queries"
        );
        assert!(
            HTML.contains("'ResolvePersonaProposal'"),
            "must construct ResolvePersonaProposal envelopes"
        );
        // Three resolution kinds wired in the UI.
        assert!(
            HTML.contains("'Approve'"),
            "must offer the Approve resolution"
        );
        assert!(
            HTML.contains("'ApproveWithEdit'"),
            "must offer the ApproveWithEdit (Q3a edit-then-approve) resolution"
        );
        assert!(
            HTML.contains("'Reject'"),
            "must offer the Reject resolution"
        );
        // Response handler.
        assert!(
            HTML.contains("'PersonaProposalResolved'"),
            "must dispatch on PersonaProposalResolved type"
        );
    }

    /// Phase 69 — the embedded HTML must wire the desktop
    /// notification handler, the permission prompt banner, and
    /// the in-page toast stack. Substring smoke tests guard
    /// against accidental gutting of the Reach-Phase-4 surface.
    #[test]
    fn html_contains_phase_69_desktop_notification_wiring() {
        // WS receive-side handler.
        assert!(
            HTML.contains("'DesktopNotification'"),
            "must dispatch on DesktopNotification type"
        );
        assert!(
            HTML.contains("showDesktopNotification"),
            "must define the browser-Notification helper"
        );
        assert!(
            HTML.contains("showToast"),
            "must define the in-page toast helper"
        );
        // Permission prompt + banner controls.
        assert!(
            HTML.contains("notif-permission-banner"),
            "must include the permission prompt banner element"
        );
        assert!(
            HTML.contains("Notification.requestPermission"),
            "must request browser notification permission"
        );
        // Toast stack container.
        assert!(
            HTML.contains("toast-stack"),
            "must include the toast stack container"
        );
    }
}
