//! Chapter M.5 — embed the `aivyx-web` Dioxus bundle into the daemon binary.
//!
//! If `crates/aivyx-web/dist/` exists (built by `just build-web` / CI via
//! `dx bundle`), every file under it is embedded with `include_bytes!` into a
//! generated `WEB_ASSETS` table (path, bytes, MIME). If it does NOT exist — the
//! normal case for a plain `cargo build`, which must not need a wasm toolchain —
//! the table is empty and the daemon serves a "run `just build-web`" fallback.
//!
//! This is the only thing that reads the wasm bundle; nothing else in the
//! daemon build depends on the web toolchain.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dist = Path::new(&manifest).join("../aivyx-web/dist");

    // Rebuild the embed whenever the bundle changes (or first appears).
    println!("cargo:rerun-if-changed={}", dist.display());

    let mut code = String::from(
        "// @generated by build.rs — the embedded aivyx-web bundle (Chapter M.5).\n\
         /// (path, bytes, content-type) for every file in the web bundle, or\n\
         /// empty when `crates/aivyx-web/dist/` has not been built.\n\
         pub static WEB_ASSETS: &[(&str, &[u8], &str)] = &[\n",
    );
    if dist.is_dir() {
        if let Ok(canon) = fs::canonicalize(&dist) {
            collect(&canon, &canon, &mut code);
        }
    }
    code.push_str("];\n");

    fs::write(Path::new(&out_dir).join("web_assets.rs"), code).expect("write web_assets.rs");
}

/// Recursively emit one `WEB_ASSETS` entry per file under `dir`, with the path
/// relative to `base` (leading `/`) and a content-type guessed by extension.
fn collect(base: &Path, dir: &Path, code: &mut String) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(base, &path, code);
            continue;
        }
        let Ok(rel) = path.strip_prefix(base) else {
            continue;
        };
        let url = format!("/{}", rel.to_string_lossy().replace('\\', "/"));
        let mime = content_type(&path);
        // `{:?}` produces a valid Rust string literal for both the URL and the
        // absolute include path.
        code.push_str(&format!(
            "    ({url:?}, include_bytes!({:?}), {mime:?}),\n",
            path.to_string_lossy()
        ));
    }
}

fn content_type(path: &Path) -> &'static str {
    match path.extension().and_then(|e| e.to_str()) {
        Some("html") => "text/html; charset=utf-8",
        Some("js") => "text/javascript; charset=utf-8",
        Some("wasm") => "application/wasm",
        Some("css") => "text/css; charset=utf-8",
        Some("json") => "application/json",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("ico") => "image/x-icon",
        Some("woff2") => "font/woff2",
        _ => "application/octet-stream",
    }
}
